const { ok } = require('../lib/http');

// FBS D1 teams grouped by conference (2024 season) with ESPN team IDs
const FBS_TEAMS = [
  {
    conference: 'ACC',
    teams: [
      { id: '103', name: 'Boston College Eagles' },
      { id: '25',  name: 'California Golden Bears' },
      { id: '228', name: 'Clemson Tigers' },
      { id: '150', name: 'Duke Blue Devils' },
      { id: '52',  name: 'Florida State Seminoles' },
      { id: '59',  name: 'Georgia Tech Yellow Jackets' },
      { id: '97',  name: 'Louisville Cardinals' },
      { id: '2390',name: 'Miami Hurricanes' },
      { id: '152', name: 'NC State Wolfpack' },
      { id: '153', name: 'North Carolina Tar Heels' },
      { id: '221', name: 'Pittsburgh Panthers' },
      { id: '2567',name: 'SMU Mustangs' },
      { id: '24',  name: 'Stanford Cardinal' },
      { id: '183', name: 'Syracuse Orange' },
      { id: '258', name: 'Virginia Cavaliers' },
      { id: '259', name: 'Virginia Tech Hokies' },
      { id: '154', name: 'Wake Forest Demon Deacons' },
    ],
  },
  {
    conference: 'American Athletic',
    teams: [
      { id: '349',  name: 'Army Black Knights' },
      { id: '2429', name: 'Charlotte 49ers' },
      { id: '151',  name: 'East Carolina Pirates' },
      { id: '2226', name: 'Florida Atlantic Owls' },
      { id: '235',  name: 'Memphis Tigers' },
      { id: '2426', name: 'Navy Midshipmen' },
      { id: '249',  name: 'North Texas Mean Green' },
      { id: '242',  name: 'Rice Owls' },
      { id: '58',   name: 'South Florida Bulls' },
      { id: '218',  name: 'Temple Owls' },
      { id: '2655', name: 'Tulane Green Wave' },
      { id: '202',  name: 'Tulsa Golden Hurricane' },
      { id: '5',    name: 'UAB Blazers' },
      { id: '2636', name: 'UTSA Roadrunners' },
    ],
  },
  {
    conference: 'Big 12',
    teams: [
      { id: '12',   name: 'Arizona Wildcats' },
      { id: '9',    name: 'Arizona State Sun Devils' },
      { id: '239',  name: 'Baylor Bears' },
      { id: '252',  name: 'BYU Cougars' },
      { id: '2132', name: 'Cincinnati Bearcats' },
      { id: '38',   name: 'Colorado Buffaloes' },
      { id: '248',  name: 'Houston Cougars' },
      { id: '66',   name: 'Iowa State Cyclones' },
      { id: '2305', name: 'Kansas Jayhawks' },
      { id: '2306', name: 'Kansas State Wildcats' },
      { id: '197',  name: 'Oklahoma State Cowboys' },
      { id: '2628', name: 'TCU Horned Frogs' },
      { id: '2641', name: 'Texas Tech Red Raiders' },
      { id: '2116', name: 'UCF Knights' },
      { id: '254',  name: 'Utah Utes' },
      { id: '277',  name: 'West Virginia Mountaineers' },
    ],
  },
  {
    conference: 'Big Ten',
    teams: [
      { id: '356',  name: 'Illinois Fighting Illini' },
      { id: '84',   name: 'Indiana Hoosiers' },
      { id: '2294', name: 'Iowa Hawkeyes' },
      { id: '120',  name: 'Maryland Terrapins' },
      { id: '127',  name: 'Michigan State Spartans' },
      { id: '130',  name: 'Michigan Wolverines' },
      { id: '135',  name: 'Minnesota Golden Gophers' },
      { id: '158',  name: 'Nebraska Cornhuskers' },
      { id: '77',   name: 'Northwestern Wildcats' },
      { id: '194',  name: 'Ohio State Buckeyes' },
      { id: '2483', name: 'Oregon Ducks' },
      { id: '213',  name: 'Penn State Nittany Lions' },
      { id: '2509', name: 'Purdue Boilermakers' },
      { id: '164',  name: 'Rutgers Scarlet Knights' },
      { id: '26',   name: 'UCLA Bruins' },
      { id: '30',   name: 'USC Trojans' },
      { id: '264',  name: 'Washington Huskies' },
      { id: '275',  name: 'Wisconsin Badgers' },
    ],
  },
  {
    conference: 'Conference USA',
    teams: [
      { id: '2229', name: 'FIU Panthers' },
      { id: '55',   name: 'Jacksonville State Gamecocks' },
      { id: '338',  name: 'Kennesaw State Owls' },
      { id: '2335', name: 'Liberty Flames' },
      { id: '2348', name: 'Louisiana Tech Bulldogs' },
      { id: '2393', name: 'Middle Tennessee Blue Raiders' },
      { id: '166',  name: 'New Mexico State Aggies' },
      { id: '2534', name: 'Sam Houston Bearkats' },
      { id: '2638', name: 'UTEP Miners' },
      { id: '98',   name: 'Western Kentucky Hilltoppers' },
    ],
  },
  {
    conference: 'Mid-American',
    teams: [
      { id: '2006', name: 'Akron Zips' },
      { id: '2050', name: 'Ball State Cardinals' },
      { id: '189',  name: 'Bowling Green Falcons' },
      { id: '2084', name: 'Buffalo Bulls' },
      { id: '2117', name: 'Central Michigan Chippewas' },
      { id: '2199', name: 'Eastern Michigan Eagles' },
      { id: '2309', name: 'Kent State Golden Flashes' },
      { id: '193',  name: 'Miami (OH) RedHawks' },
      { id: '2459', name: 'Northern Illinois Huskies' },
      { id: '195',  name: 'Ohio Bobcats' },
      { id: '2649', name: 'Toledo Rockets' },
      { id: '2711', name: 'Western Michigan Broncos' },
    ],
  },
  {
    conference: 'Mountain West',
    teams: [
      { id: '2005', name: 'Air Force Falcons' },
      { id: '68',   name: 'Boise State Broncos' },
      { id: '36',   name: 'Colorado State Rams' },
      { id: '278',  name: 'Fresno State Bulldogs' },
      { id: '62',   name: "Hawai'i Rainbow Warriors" },
      { id: '2440', name: 'Nevada Wolf Pack' },
      { id: '167',  name: 'New Mexico Lobos' },
      { id: '21',   name: 'San Diego State Aztecs' },
      { id: '23',   name: 'San José State Spartans' },
      { id: '2439', name: 'UNLV Rebels' },
      { id: '328',  name: 'Utah State Aggies' },
      { id: '2751', name: 'Wyoming Cowboys' },
    ],
  },
  {
    conference: 'SEC',
    teams: [
      { id: '333',  name: 'Alabama Crimson Tide' },
      { id: '8',    name: 'Arkansas Razorbacks' },
      { id: '2',    name: 'Auburn Tigers' },
      { id: '57',   name: 'Florida Gators' },
      { id: '61',   name: 'Georgia Bulldogs' },
      { id: '96',   name: 'Kentucky Wildcats' },
      { id: '99',   name: 'LSU Tigers' },
      { id: '344',  name: 'Mississippi State Bulldogs' },
      { id: '142',  name: 'Missouri Tigers' },
      { id: '201',  name: 'Oklahoma Sooners' },
      { id: '145',  name: 'Ole Miss Rebels' },
      { id: '2579', name: 'South Carolina Gamecocks' },
      { id: '2633', name: 'Tennessee Volunteers' },
      { id: '251',  name: 'Texas Longhorns' },
      { id: '245',  name: 'Texas A&M Aggies' },
      { id: '238',  name: 'Vanderbilt Commodores' },
    ],
  },
  {
    conference: 'Sun Belt',
    teams: [
      { id: '2026', name: 'Appalachian State Mountaineers' },
      { id: '2032', name: 'Arkansas State Red Wolves' },
      { id: '324',  name: 'Coastal Carolina Chanticleers' },
      { id: '290',  name: 'Georgia Southern Eagles' },
      { id: '2247', name: 'Georgia State Panthers' },
      { id: '256',  name: 'James Madison Dukes' },
      { id: '309',  name: "Louisiana Ragin' Cajuns" },
      { id: '276',  name: 'Marshall Thundering Herd' },
      { id: '295',  name: 'Old Dominion Monarchs' },
      { id: '6',    name: 'South Alabama Jaguars' },
      { id: '2572', name: 'Southern Miss Golden Eagles' },
      { id: '326',  name: 'Texas State Bobcats' },
      { id: '2653', name: 'Troy Trojans' },
    ],
  },
  {
    conference: 'Independents',
    teams: [
      { id: '41',  name: 'Connecticut Huskies' },
      { id: '113', name: 'Massachusetts Minutemen' },
      { id: '87',  name: 'Notre Dame Fighting Irish' },
    ],
  },
];

exports.handler = async () => ok(FBS_TEAMS);

